### PR TITLE
makefile: "-lgslcblas" is required to link with gsl

### PR DESCRIPTION
**Pull request by liweitianux**
* include ``-lm`` within gsl library as well, e.g.,
  ``pkg-config --libs gsl`` gives ``-lgsl -lgslcblas -lm``
* remove the unused ``flags2`` variable

### CODE REVIEW

**Comment by mariogrs** [comment]
yes, I think the makefile needs to be a bit more sophisticated. It compiled fine on my mac. Also, some installations use omp instead of pthreads.

**Comment by liweitianux** [comment]
Hi @mariogrs ,

Thanks for merge this patch.

As for the *OpenMP* and *POSIX threads* (i.e., pthreads), they are two **different** techniques to achieve the parallel programming.  The latter is generally limited to UNIX/Linux systems, while the former is more generic and is supported on more platforms, e.g., Windows.

Since we already use ``gcc -fopenmp`` here, i.e., we choose the OpenMP, so we can just carry on to use the OMP version of FFTW3 libraries.  In addition, on my Debian Linux system, both the OMP and pthreads versions of FFTW3 libraries are packaged in the same package ``libfftw3-double3``:

```
% dpkg -S /usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3.5.5
libfftw3-double3:amd64: /usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3.5.5
% dpkg -S /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3.5.5
libfftw3-double3:amd64: /usr/lib/x86_64-linux-gnu/libfftw3_threads.so.3.5.5
```

Cheers,
Aly

**Comment by liweitianux** [comment]
Had a further look at the OpenMP version of FFTW3 library, I found it also linked to ``libpthread.so.0``.  So it seems, as for the Linux platform, that "pthreads" is the lower-level implementation/support of the OpenMP.  Maybe it is something different for other platforms.

```
% ldd /usr/lib/x86_64-linux-gnu/libfftw3_omp.so.3.5.5
	linux-vdso.so.1 (0x00007ffd3ec5a000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f68bdf4f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f68bdc4b000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f68bda1e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f68bd801000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f68bd463000)
	/lib64/ld-linux-x86-64.so.2 (0x000055b1a0bcf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f68bd25d000)
```

**Comment by mariogrs** [comment]
Yes, so the problem I had at the time was that I couldn't get the omp fftw version to compile on my mac, hence I kept the threads version. On Linux systems, the omp version works fine.

**Pull request merged**
