### PR TITLE
fix search path

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by liweitianux** [comment]
Hi @gijzelaerr ,

I propose to use ``#!/bin/sh`` instead of ``#!/bin/bash``, and then ``DIR="${0%/*}"``, to be more generic and simple.

Cheers,
Aly

**Comment by mariogrs** [comment]
This DIR="${0%/*}" won't give you the full search path...

**Comment by mariogrs** [comment]
My bad, it works fine, thanks Aly.

**Comment by liweitianux** [comment]
Glad to hear it helps :-) @mariogrs .

**Pull request merged**
